[package]
name = "prayer"
version = "0.1.0"
authors = ["Carlo <CRefice@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
itertools = "*"
nalgebra-glm = { version = "*", features = ["serde-serialize"] }
rand = "*"
rayon = "*"
serde = { version = "*", features = ["derive"] }
toml = "*"
