[params]
resolution = [800, 800]
samples = 1000
max_light_bounces = 8
camera_pos = [-0.6, 0.3, -0.4666]
looking_at = [0.1, 0.0, 0.0]

[scene]
environment = "textures/sunset.hdr"
[[scene.objects]]
geometry = "meshes/dragon.obj"
material = { albedo = [0.9, 0.69, 0.22], metalness = 1.0, roughness = 0.3 }
