[params]
resolution = [800, 800]
samples = 200
max_light_bounces = 7
gamma = 2.2
exposure = 1.0

[scene]
environment = [0.5, 0.5, 0.7]
[[scene.objects]]
geometry = { points = [[-5,-3,-6], [-5,-3,6], [5,-3,6], [5,-3,-6]] }
material = { albedo = [1, 0, 0], metalness = 0, roughness = 1 }
[[scene.objects]]
geometry = { points = [[-2,4,-6], [-2,4,6], [-2,-3,6], [-2,-3,-6]] }
material = { albedo = [1,1,1], metalness = 0, roughness = 1, emission = [0,0,0] }
